### ISSUE TITLE
androidx在哪里下载？

### ISSUE THREAD

**Issue by mosentest** [rongcloud/callkit-android#3]
androidx在哪里下载？

**Comment by mosentest** [comment]
import cn.rongcloud.rtc.CenterManager;

这类没有


    api 'cn.rongcloud.sdk:im_lib:4.0.3.2' // 即时通讯基础能力库
    api 'cn.rongcloud.sdk:im_kit:4.0.3.2' // 即时通讯 UI 基础组件
    api 'cn.rongcloud.sdk:call_kit:4.0.3.3' // 音视频通话能力 UI 组件
    api 'cn.rongcloud.sdk:call_lib:4.0.3.3' // 音视频呼叫信令

    api 'com.github.bumptech.glide:glide:4.10.0'
    api 'com.google.code.gson:gson:2.8.6'

**Comment by mosentest** [comment]
import cn.rongcloud.rtc.RongRTCConfig;

**Comment by HuichaoLi** [comment]
这个项目的CallKit代码处于停更状态，CallKit已经在融云官网开源，可以直接在官网下载：
https://www.rongcloud.cn/downloads
![image](https://user-images.githubusercontent.com/8872640/97558692-6b32e680-1a17-11eb-93e9-d39a14762358.png)

**Comment by HuichaoLi** [comment]
> androidx在哪里下载？

融云目前不直接提供Android X 版本的CallKit。项目中如果是maven依赖的话，是可以直接用，不需要转Android X的。如果是直接下载的 CallKit源码，转换方式参考：
https://support.rongcloud.cn/ks/MTA2OA==
